[book]
authors = ["Iwan Kurniawan"]
language = "id"
src = "src"
title = "Tonsilektomi"
description = "Panduan medis dan komprehensif mengenai indikasi, prosedur bedah, perawatan pasca-operasi, serta komplikasi tonsilektomi."

[preprocessor.dawnbook]
optional = true
subject_label = "Kedokteran"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
