[book]
authors = ["Iwan Kurniawan"]
language = "id"
src = "src"
title = "Resiliensi dan Ketangguhan"

[preprocessor.dawnbook]
optional = true
subject_label = "Psikologi"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
