[book]
authors = ["Placeholder Author"]
language = "en"
src = "src"
title = "Template Book"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header-v5.css"]
additional-js = ["../shared-script-v3.js"]
