[book]
authors = ["Iwan Kurniawan"]
language = "en"
src = "src"
title = "Placeholder Title"
description = "Placeholder description for book SEO meta tag."

[preprocessor.dawnbook]
optional = true
subject_label = "Placeholder"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
