[book]
authors = ["Iwan Kurniawan"]
language = "id"
src = "src"
title = "Logika dan Penalaran Kritis"
description = "Kuasai ilmu logika dan penalaran kritis untuk mengidentifikasi kekeliruan berpikir (fallacy), mengevaluasi argumen, dan berpikir analitis."

[preprocessor.dawnbook]
optional = true
subject_label = "Filsafat"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
