[book]
authors = ["Iwan Kurniawan"]
language = "id"
src = "src"
title = "Pembelajaran Multidisiplin: Menghubungkan Pikiran, Menembus Batas Ilmu"
description = "Panduan pembelajaran multidisiplin dalam menghubungkan berbagai cabang ilmu untuk memecahkan masalah kompleks abad 21."

[preprocessor.dawnbook]
optional = true
subject_label = "Kurikulum dan Teknologi Pendidikan"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
