[book]
authors = ["Tedi Rahmat"]
language = "en"
src = "src"
title = "Filosofi Stoikisme"

[preprocessor.dawnbook]
optional = true
subject_label = "Filsafat"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
