// AUTO-GENERATED by scripts/builder/stats-aggregator.ts at build time.
// Do not edit manually. Regenerated on every `bun run scripts/build.ts`.

export const BUILT_TOTAL_CHAPTERS = 599;

export const BUILT_CONTRIBUTORS = {
  total: 2,
  top: [
    { name: "Iwan Kurniawan", books: 41 },
    { name: "Kania Salsabila", books: 6 },
  ],
};
