/**
 * scripts/builder/stats-aggregator.ts
 *
 * Computes stats that cannot be derived from D1 at the edge:
 *   - total_chapters (sum of SUMMARY.md chapter entries across books/)
 *   - contributors (top + total) from `git shortlog -sn --all`
 *
 * Output: writes a TS module at functions/lib/built-stats.ts that the
 * /api/stats Cloudflare Pages Function imports at runtime. Doing it this way
 * means no KV/R2 binding and no JSON parse on the edge — the constants are
 * bundled with the function code itself.
 */

import { readFile, readdir, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { $ } from "bun";

export interface ContributorSummary {
  total: number;
  top: { name: string; commits: number }[];
}

export interface BuiltStats {
  totalChapters: number;
  contributors: ContributorSummary;
}

/**
 * Counts published chapters by scanning each book's SUMMARY.md for list items
 * (lines starting with "- [") — mirrors the chapter-count logic in
 * scripts/builder/metadata.ts.
 */
async function countTotalChapters(booksDir: string): Promise<number> {
  let total = 0;
  let entries: string[];
  try {
    entries = await readdir(booksDir);
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const bookPath = join(booksDir, entry);
    try {
      const s = await stat(bookPath);
      if (!s.isDirectory()) continue;
    } catch {
      continue;
    }
    if (entry.startsWith("_")) continue; // skip _template, etc.
    try {
      const summary = await readFile(join(bookPath, "src", "SUMMARY.md"), "utf8");
      const count = summary
        .split("\n")
        .filter((line) => line.trim().startsWith("- [")).length;
      total += count;
    } catch {
      // No SUMMARY.md → skip silently
    }
  }
  return total;
}

/**
 * Runs `git shortlog -sn --all` to get a top-contributors list.
 * Format: "<count>\t<Name>"
 */
async function readGitContributors(topN: number = 5): Promise<ContributorSummary> {
  try {
    const out = await $`git shortlog -sn --all`.quiet().text();
    const lines = out.trim().split("\n").filter(Boolean);
    const all = lines.map((line) => {
      const m = line.trim().match(/^(\d+)\s+(.+)$/);
      if (!m) return null;
      const commits = parseInt(m[1], 10);
      const name = m[2].trim();
      if (!commits || !name) return null;
      return { name, commits };
    }).filter((x): x is { name: string; commits: number } => x !== null);
    // `git shortlog` already aggregates by name (canonicalizes), so no extra
    // dedupe needed beyond what git itself does.
    return {
      total: all.length,
      top: all.slice(0, topN),
    };
  } catch {
    return { total: 0, top: [] };
  }
}

/**
 * Computes and writes functions/lib/built-stats.ts. Returns the stats for
 * the caller (build.ts) so it can log or pass to the template engine.
 */
export async function writeBuiltStats(
  rootDir: string,
): Promise<BuiltStats> {
  const booksDir = join(rootDir, "books");
  const totalChapters = await countTotalChapters(booksDir);
  const contributors = await readGitContributors(5);

  const target = join(rootDir, "functions", "lib", "built-stats.ts");
  // Escape contributor names defensively (TypeScript string literal escaping).
  const escapeTs = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const topJson = contributors.top
    .map((c) => `    { name: "${escapeTs(c.name)}", commits: ${c.commits} },`)
    .join("\n");
  const body = `// AUTO-GENERATED by scripts/builder/stats-aggregator.ts at build time.
// Do not edit manually. Regenerated on every \`bun run scripts/build.ts\`.

export const BUILT_TOTAL_CHAPTERS = ${totalChapters};

export const BUILT_CONTRIBUTORS = {
  total: ${contributors.total},
  top: [
${topJson}
  ],
};
`;
  await writeFile(target, body, "utf8");

  return { totalChapters, contributors };
}
