/**
 * scripts/builder/stats-aggregator.ts
 *
 * Computes stats that cannot be derived from D1 at the edge:
 *   - total_chapters (sum of SUMMARY.md chapter entries across books/)
 *   - contributors (top + total) ranked by published book count, parsed
 *     from each `books/<slug>/book.toml` `[book].authors` array
 *
 * Output: writes a TS module at functions/lib/built-stats.ts that the
 * /api/stats Cloudflare Pages Function imports at runtime. Doing it this way
 * means no KV/R2 binding and no JSON parse on the edge — the constants are
 * bundled with the function code itself.
 */

import { readFile, readdir, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";

export interface ContributorSummary {
  total: number;
  top: { name: string; books: number }[];
}

export interface BuiltStats {
  totalChapters: number;
  contributors: ContributorSummary;
}

/**
 * Counts published chapters by scanning each book's SUMMARY.md for list items
 * (lines starting with "- [") — mirrors the chapter-count logic in
 * scripts/builder/metadata.ts.
 */
async function countTotalChapters(booksDir: string): Promise<number> {
  let total = 0;
  let entries: string[];
  try {
    entries = await readdir(booksDir);
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const bookPath = join(booksDir, entry);
    try {
      const s = await stat(bookPath);
      if (!s.isDirectory()) continue;
    } catch {
      continue;
    }
    if (entry.startsWith("_")) continue; // skip _template, etc.
    try {
      const summary = await readFile(join(bookPath, "src", "SUMMARY.md"), "utf8");
      const count = summary
        .split("\n")
        .filter((line) => line.trim().startsWith("- [")).length;
      total += count;
    } catch {
      // No SUMMARY.md → skip silently
    }
  }
  return total;
}

/**
 * Parses the `authors` array from a single book.toml. Supports both single
 * and multi-author forms:
 *
 *   authors = ["Iwan Kurniawan"]
 *   authors = ["Iwan Kurniawan", "Kania Salsabila"]
 *
 * Returns a normalized, trimmed, deduplicated list of names. Empty entries
 * are dropped.
 */
function parseAuthors(bookToml: string): string[] {
  // Match the full `[...]` block following `authors =`.
  const m = bookToml.match(/authors\s*=\s*\[([\s\S]*?)\]/);
  if (!m) return [];
  const inner = m[1];
  const names: string[] = [];
  for (const raw of inner.split(",")) {
    const s = raw.trim().replace(/^"|"$/g, "");
    if (s) names.push(s);
  }
  // Dedupe while preserving insertion order.
  return Array.from(new Set(names));
}

/**
 * Reads each `books/<slug>/book.toml` and counts how many published books
 * each author has authored. Only book directories that look like real books
 * (not `_template`) are counted.
 *
 * Each author on a multi-author book gets +1 credit.
 */
async function readAuthorsByBookCount(
  booksDir: string,
  topN: number = 5,
): Promise<ContributorSummary> {
  let entries: string[];
  try {
  entries = await readdir(booksDir);
  } catch {
    return { total: 0, top: [] };
  }
  const counts = new Map<string, number>();
  for (const entry of entries) {
    if (entry.startsWith("_")) continue;
    const bookPath = join(booksDir, entry);
    try {
      const s = await stat(bookPath);
      if (!s.isDirectory()) continue;
    } catch {
      continue;
    }
    let bookToml: string;
    try {
      bookToml = await readFile(join(bookPath, "book.toml"), "utf8");
    } catch {
      continue;
    }
    const authors = parseAuthors(bookToml);
    if (authors.length === 0) continue;
    for (const name of authors) {
      counts.set(name, (counts.get(name) ?? 0) + 1);
    }
  }

  const all = Array.from(counts.entries())
    .map(([name, books]) => ({ name, books }))
    .sort((a, b) => b.books - a.books || a.name.localeCompare(b.name));

  return {
    total: all.length,
    top: all.slice(0, topN),
  };
}

/**
 * Computes and writes functions/lib/built-stats.ts. Returns the stats for
 * the caller (build.ts) so it can log or pass to the template engine.
 */
export async function writeBuiltStats(
  rootDir: string,
): Promise<BuiltStats> {
  const booksDir = join(rootDir, "books");
  const totalChapters = await countTotalChapters(booksDir);
  const contributors = await readAuthorsByBookCount(booksDir, 5);

  const target = join(rootDir, "functions", "lib", "built-stats.ts");
  // Escape contributor names defensively (TypeScript string literal escaping).
  const escapeTs = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const topJson = contributors.top
    .map((c) => `    { name: "${escapeTs(c.name)}", books: ${c.books} },`)
    .join("\n");
  const body = `// AUTO-GENERATED by scripts/builder/stats-aggregator.ts at build time.
// Do not edit manually. Regenerated on every \`bun run scripts/build.ts\`.

export const BUILT_TOTAL_CHAPTERS = ${totalChapters};

export const BUILT_CONTRIBUTORS = {
  total: ${contributors.total},
  top: [
${topJson}
  ],
};
`;
  await writeFile(target, body, "utf8");

  return { totalChapters, contributors };
}
