[book]
authors = ["Tedi Rahmat"]
language = "id"
src = "src"
title = "Neuroplastisitas dalam Belajar"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header-v4.css"]
additional-js = ["../shared-script-v3.js"]
