[book]
authors = ["Tedi Rahmat"]
language = "id"
src = "src"
title = "Teori Perkembangan Kognitif Piaget"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header-v6.css"]
additional-js = ["../shared-script-v3.js"]
