name: Validate Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.37'

      - name: Install Dependencies
        run: bun install

      - name: Build All Books
        run: bun run build
