[book]
authors = ["Iwan Kurniawan"]
language = "id"
src = "src"
title = "Human Capital Theory"
description = "Memahami konsep Human Capital Theory, investasi pada pendidikan dan pelatihan, serta dampaknya terhadap produktivitas dan ekonomi."

[preprocessor.dawnbook]
optional = true
subject_label = "Manajemen"

[output.html.print]
enable = false

[output.html]
mathjax-support = true
additional-css = ["../shared-header.css", "../../apps/hub/src/styles/typography.css"]
additional-js = ["../shared-script.js"]
